services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass Huy-1011

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.env
    ports:
      - '10001:10001'
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '10002:10002'
    volumes:
      - .:/usr/src/app

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: npm run start:dev notification
    env_file:
      - ./apps/notification/.env
    ports:
      - '10003:10003'
    volumes:
      - .:/usr/src/app

  aws-s3:
    build:
      context: .
      dockerfile: ./apps/aws-s3/Dockerfile
      target: development
    command: npm run start:dev aws-s3
    env_file:
      - ./apps/aws-s3/.env
    ports:
      - '10004:10004'
    volumes:
      - .:/usr/src/app

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - '10000:10000'
    volumes:
      - .:/usr/src/app

volumes:
  redis_data:
  mongo_data: