apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reporting
  name: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - image: 654654586768.dkr.ecr.ap-southeast-2.amazonaws.com/reporting:latest
          name: reporting
