apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: message
  name: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - image: 654654586768.dkr.ecr.ap-southeast-2.amazonaws.com/message:latest
          name: message
