apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feed
  name: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - image: 654654586768.dkr.ecr.ap-southeast-2.amazonaws.com/feed:latest
          name: feed
